# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_pb2 as proto__pb2


class baseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.exchange = channel.unary_unary(
                '/baseService/exchange',
                request_serializer=proto__pb2.Request.SerializeToString,
                response_deserializer=proto__pb2.Response.FromString,
                )


class baseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def exchange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_baseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'exchange': grpc.unary_unary_rpc_method_handler(
                    servicer.exchange,
                    request_deserializer=proto__pb2.Request.FromString,
                    response_serializer=proto__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class baseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def exchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/baseService/exchange',
            proto__pb2.Request.SerializeToString,
            proto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
